version: '3.3'

services:
#  app:
#    container_name: spring-rest-api
#    build: .
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network
#    depends_on:
#      - postgres
#      - redis

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge