# Application properties file in yaml format
server:
  servlet:
    # defines url prefix
    context-path: /planets-api
  # defines port to run
  port: 8080
spring:
  main:
    # desables spring logo on console
    banner-mode: 'off'

  
# Cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
# MongoDB    
  data:
    mongodb:
      uri: mongodb://localhost:27017/planets 

      